# 자료형

In [ ]:
a=10
# 변수 지우기

# 표준입력장치로 실수를 입력받아서 정수로 변환하기

# 표준출력장치
# 문자열 - %?
# 정수 - %?
# 실수 - %?

# 외부상수받기
name = "홍길동"
age=25
tall=175.456
# 이름:홍길동, 나이:25, data:175.45 로 출력되게 하는 3가지 방법

# 변수를 만들때 3가지 방법
# camelcase를 camel표기법으로
# snakecase를 snake표기법으로
# pascalcase를 pascal표기법으로

# 여러줄의
# 문장을
# 한번에 변수에 넣기

string = "Life is too short, You need python"
# 인덱싱으로 f 추출하기
# 인덱싱으로 short 추출하기
# 인덱싱으로 life 추출하기
# 인덱싱으로 python 추출하기
# d가 몇번째에 있는지 확인하는 방법
# d의 인덱스 번호 확인
# ['Life', 'is', 'too', 'short,', 'You', 'need', 'python'] 가 반환되게

# 대문자로
# 소문자로

abc = 'abcdefg'
# 'a,b,c,d,e,f,g' 반환되게
# 이어서 ['a', 'b', 'c', 'd', 'e', 'f', 'g'] 가 반환되게

hz = "홀짝홀짝홀짝"
# 홀홀홀 반환되게

# 표준입력장치로 사용자의 영문이름을 한번에 입력받아서 성과 이름 순서를 바꾸어 출력하는 프로그램을 작성
# hong gildong -> gildong hong (2가지 방법)

# 이스케이프 문자
# 'c:\python38\test' 출력하는 법 (2가지 방법)

# ', " 를 문자로 인식하는 법
# "naver", "kakao", "sk", "samsung" 를
# naver/kakao/sk/samsung 반환해주는 프린트 문 작성

# 자료형태

In [ ]:
a1=[1,4,3,2]

# 5를 추가
# 4와 3사이에 5추가 (2가지 방법)
# 4 제거 (2가지 방법)
# a1에 5가 몇개인지 보는 방법

# 역순으로 추출되게 [5,2,3,5,4,1]
# 오름차순 정렬
# 내림차순 정렬

a2=[1,2,3]

# [1,2,3,[4,5,6,7]]으로 출력 (2가지 방법)
# a2의 원소의 개수
# 3의 인덱스 번호 추출

wishlist = ['가방', '시계', '신발']
# mycart라는 새로운 리스트를 만들고 시계와 신발을 추출
# wishlist 시계랑 신발은 삭제 (2가지 방법)

a3 = [4,5,6]
# a3 언패킹 : x, y, z 에 각각 4, 5, 6 할당하기

movie_rank = ['닥터스트레인지', '스프릿', '럭키']
# 배트맨을 추가
# 슈퍼맨을 닥터스트레인지와 스프릿 사이에 넣으세요 (2가지 방법)

# 튜플을 1~10까지 만들고 짝수만 슬라이싱하여 출력
# (2,4,6,8,10)

apart1 = [[101, 102],[201, 202],[301, 302]]
# 101호
# 102호
# ...
# 302호

lst = [1,2,3,4,5,3,4,5]
# 항목수
# 합계
# 최소값
# 최대값
# 3의 개수
# 평균 (계산식)

s1 = set([1,2,3,4,5,6])
s2 = set([4,5,6,7,8,9])

# 교집합 (2가지 방법)
# 합집합 (2가지 방법)
# 차집합 (2가지 방법, 2가지 버전)

s3 = set([1,2,3])

# 원소 4 추가
# 5,6,7 한번에 추가
# 7제거 (2가지 방법 - 한개 방법은 없는 값을 지우려해도 오류가 뜨지 않음)

# 딕셔너리 만드는 3가지 방법
# {'김밥': 3000, '떡볶이': 2000, '어묵': 3500, '튀김': 2800}

alphabet={'a':'apple','b':'banana','c':'car','e':'error'}
# e,error 제외시키기
# 키 c의 값 cool로 변경
# 키 d와 값 dog 추가

# 키 a의 값 확인 (기본)
# 원소에 없는 키 f의 값 확인 시 오류가 안뜨게 확인하는 법
# 원소에 없는 키 f의 값 확인 시 오류가 안뜨게 하되, food가 추출되게 (단, alphabet 내용은 변하지 않게)
# 원소에 없는 키 f의 값 확인 시 alphabet에 키 f가 추가되고 값은 food로 넣는 방법

# alphabet의 키 추출
# alphabet의 값 추출
# alphabet의 키와 값 둘다 추출
# alphabet의 한번에 모든 내용 삭제

charset = ['abc', 'code', 'band', 'band', 'abc']
# wc = {'abc':2, band:2, code:1} 가 추출되게

# 조건문 반복문

In [ ]:
# 표준입력장치로 점수를 입력받아서
# 100~90점 A
# 89~80점 B
# 79~70점 C
# 70점 이하 F
# 출력하는 조건문을 만드시오

pokect = ['paper', 'cellphone', 'money']
# 만약에 주머니에 돈이 있으면 택시를 타고 없으면 걸어가라

# 출생 연도를 표준입력장치로 받아서
#     ~1924 가장 위대한 세대(The Greatest Generation)
# 1925~1945 침묵 세대(The Silent Generation)
# 1946~1964 베이비 부머(baby boomer)
# 1965~1980 X세대(Generation X)
# 1981~1996 밀레니얼(millennial)
# 1997~     Z세대(Generation Z)
# 당신의 세대는 00 세대입니다. 출력

# 길이, 부피, 무게나 금액을 표기할 때 1000을
# 'k'로 표기하곤 합니다. 입력은 10의 n제곱 입력하세요.
# 예를 들어, 3000m는 3km로 표기하는 것이 일반적입니다.
# 다음은 입력받은 숫자가 1000보다 크면 1자리부터
# 100자리까지의 숫자를 생략하고 'k'를 붙여주는
# 파이썬 코드입니다.
# 1000이하의 10의 n제곱을 입력하면 아무것도 수행하지 않음

# 숫자를 입력받아서 10의 배수면 프로그램 종료가 되도록 while문으로 코딩
# 11, 5676 다시입력하세요
# 110 종료
# 10의 배수가 아닌 입력받은 변수들은 리스트에 추가하여 최종 반환

# 'q'를 입력할때까지 이름을 입력받기
# q를 입력받기 전까지 입력한 내용을 리스트에 추가하여 최종 반환

# 1. 게임을 한계를 주도록 3번 이내에 맞추지 못하면 'You Lose'
# 2. 3번 내에 맞추면 'You Win!'
# 값을 바로 적용시키기 보다는 변수에 할당하는 것이 좋음

# id = 'id123', pwd = 'pwd123'
# while문으로 아이디와 패스워드를 입력받아서 id가 틀리면 id를 확인하세요
# pwd가 틀리면 pwd를 확인하세요

# 구구단 만들기
# -----[2단]-----
# 2*1=2
# 2*2=4

# while문으로 1~10의 합 구하기
# for문으로 1~10의 합 구하기

# 1. ['a','b','c']를 for 문을 사용해서 전부 대문자로 ['A','B','C']
# 2. ['dog', 'cat', 'parrot'] 첫글자만 출력 d, c, p
# 3. ['I', 'study', 'python', 'language', '!']중에서 3글자 이상인 원소 출력
# 4. 1~10까지 숫자중 모든 홀수의 합을 출력하는 for 문을 작성 1+3+5...9=합

# my_list=['가','나','다','라','마']
# 가 나
# 나 다
# 다 라
# 라 마

# if 문을 활용해서 가위바위보 게임 만들기
# 변수 가위, 바위, 보, 이겼다, 졌다, 비겼다, 나의변수, 컴퓨터변수
# if else만 사용해서

#1. elif로 다중조건문을 변환하시오
#2. mine을 표준입력장치로 변경해주세요.
#3. yours도 가위, 바위, 보를 랜덤하게 나오도록 업그레이드
#4. mine에 q를 누르면 게임 종료되도록
#5. 잘못입력한경우 잘못입력했다고 표시

# 1 ~ 100 30
# 내가 50! 다운!
# 20 업
# 업앤다운 게임을 만들어보세요
# 게임 횟수 제한

# 1~100 사이에서
# 5의 배수이면서(and) 3의 배수가 아닌 합 계산하기

#a=[1,2,3,4]
# 3을 곱하고 짝수만 result3에 넣는 코드를 작성하세요.
# [6, 12]
# for문과 리스트 내포 2가지 방법

# 구구단 코드 [2,4,6,8....3,6,9,......81]
# 리스트 내포로 만드시오.

# 클래스

In [ ]:
# 참치선물세트 속성 : 일반, 야채, 고추
# 출력 메서드
# 특별세트 (상속)
# 속성 : 일반, 햄, 카놀라유
# 출력 메서드

# 세면도구 속성 : 치약, 샴푸, 비누
# 내용물출력 메서드
# 특별세트 (상속)
# 속성 : 치약, 샴푸, 비누, 면도기
# 내용물출력 메서드

# 자동차 클래스와 객체
# 속성 : brand, model, color
# 메소드 : drive - 주행중입니다 출력
# 메소드 : trun_on - 시동을 켭니다 출력
# 메소드 : trun_off - 시동을 끕니다 출력

#1. car class 만들기
# 속성 : name, cc, year
# check 메소드를 만들고 cc가 1000미만이면 소형, 1000~2000이면 중형, 2000~ 대형
# car 객체를 만들때 car_count 개수가 하나씩 증가하도록
# car1 소나타, 2500, 2019 --> 대형 이고 car_count 실행시키면 1대
# car2 아반테, 1500, 2018 --> 중형 이고 car_count 실행시키면 2대

# car1의 이름을 확인할 수 있는 getName 메소드와
# 이름을 변경할 수 있는 setName 메소드를 추가해서 이름을 바꿔보세요.
# car1의 소나타 getName로 확인 후에 setName으로 '모닝'으로 변경하는 클래스

# 1. Character 클래스 만들기
# Character의 속성값에 Health 속성 ( 생성시 200 )
# Character 클래스 move() 메소드를 추가하고 메소드 사용시 health가 -10이 됨
# Character의 클래스 rest() 메소드를 추가하고 메소드 사용시 health +10이 됨
# 현재 health를 알 수 있는 checkHealth() method를 추가

# 2. Knight, Healer 클래스 만들기
# Knight와 Healer는 Character의 클래스를 상속
# Knight Move()를 하면 Health가 추가로 -5를 더 소모함
# Knight Attack()를 추가하고 '공격합니다.'라는 메소드를 작성

# Healer Mana라는 속성을 추가하고 생성시 100의 값을 주어짐
# Healer heal() 메소드를 추가하고 이 메소드는 Character들을 매개변수로 받음
# Healer heal() 메소드를 실행하면 Mana 가 -10이 되고
# 전달받은 Character 객체에 rest() 메소드가 실행되어 +10이 되도록 함
# Healer는 현재 마나 속성을 확인할 수 있는 Checkmana() 메소드를 추가

# 속성 : 계좌번호 '123456' (ano) / owner : 이름 (문자열) / 잔액 : balance, 비공개 속성
# method : 저금(deposit), 출금(withdraw), 조회 출력이 가능하게
# 저금(deposit) : 1000만원 이상 입금할 수 없음 (통장 최대 1000만원 한도)
# 출금(withdraw) : 잔액이 0이면 출금이 안되도록
# 조회 출력이 가능하게

#  def check_duplicate(ano)
# 사용자로부터 필요한 정보를 입력받아서 계좌 생성 - def create_account()
# 사용자로부터 필요한 정보를 입력받아서 계좌에 돈을 입금 - def deposit_account()
# 사용자로부터 필요한 정보를 입력받아서 계좌에 돈을 출금 - def withdraw_account()
# 화면 만들기
# '1:계좌생성, 2:계좌목록, 3:입금, 4:출금, 5:종료>'

# Numpy

In [ ]:
import numpy as np
# [1,4,5,8] 각 원소가 실수형인 배열 생성
# 원소의 타입과 몇 by 몇인지 확인

# Vector (1차원) 생성 [1,2,3,4]
# Matrix (2차원) 생성 [[1,2,3],[4,5,6]]
# Tensor (3차원) 생성 [[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
#                     [[13,14,15,16],[17,18,19,20],[21,22,23,24]]]

# [1,2,3] 각 원소의 타입이 float32, int8 인 배열 각각 생성

# Matrix
# 1차원 벡터로 변경 (2가지 방법)
# (3 by 2) 2차원 매트릭스로 변경
# 3 혹은 2만 사용해서 (3 by 2) 2차원 매트릭스로 변경
# 원소 5를 추출

# Tensor
# 원소 19 추출

# a = np.arange(16).reshape(4,-1)
# 결과값
# [[5,6],
#  [9,10]]

# [[5,6,7],
#  [9,10,11]]

# [[1,3],
#  [9,11]]

# x 는 앞에 3열
# y 는 마지막 열
# shape로 결과값을 보면
# x.shape ==> (4,3)
# y.shape ==> (4,)

# 배열 만들어서 다음 출력값이 나오게
# array([1, 3, 5, 7, 9])
# array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])
# 바로 윗줄 배열을 리스트 형태로 변환

# -2부터 2까지 401등분한 배열 만들기
# (2,4) 행렬을 1로 다 채우기 (정수형으로)
# (2,4) 행렬을 0으로 다 채우기 (실수형으로)

# b = np.arange(12).reshape(3,4)
# 원본 배열을 유지하면서 원소 값을 1로 다 바꾸기
# 원본 배열을 유지하면서 원소 값을 0으로 다 바꾸기

# 대각선이 1인 3 by 3 정방행렬 만들기 (원소는 정수형으로) (2가지 방법)
# 출력값
# array([[0, 0, 1, 0, 0],
#        [0, 0, 0, 1, 0],
#        [0, 0, 0, 0, 1]], dtype=int32)

# array([[0., 0., 0.],
#        [1., 0., 0.],
#        [0., 1., 0.],
#        [0., 0., 1.]])

# c = np.arange(9).reshape(3,3)
# 대각선 위치의 값을 추출 array([0, 4, 8])
# array([1, 5])

# np.random.seed(seed=1000) # 시드로 난수 생성 초기값 지정
# np.random.uniform(0, 1, 10).reshape(2,5) # 균등 분포 # 최소 최대 개수
# np.random.normal(0, 1, 10).reshape(2,5) # 정규 분포 # 평균 표준편차 개수
# np.random.binomial(n, p, size) # 이항 분포
# np.random.poisson(lam. size) np # 포아송 분포
# np.random.standard_t(df, size) np # t-분포
# np.random.f(dfnum, dfden, size) # F-분포

# d = np.arange(1,13).reshape(3,4)
# 모든 원소의 합
# 모든 행들의 합 array([10, 26, 42])
# 모든 열들의 합 array([15, 18, 21, 24])

# e = np.arange(1, 25).reshape(2,3,4)
# 모든 원소의 합
# array([[14, 16, 18, 20],
#        [22, 24, 26, 28],
#        [30, 32, 34, 36]])
# array([[15, 18, 21, 24],
#        [51, 54, 57, 60]])
# array([[10, 26, 42],
#        [58, 74, 90]])

# f = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
# 정렬 (자기 자신 바뀌지 않는 버전)
# array([[ 3,  4,  5,  7],
#        [ 1,  9, 11, 12],
#        [ 1,  2,  5, 14]])

# array([[ 1,  3,  1,  7],
#        [ 2,  5,  5,  9],
#        [ 4, 12, 11, 14]])

# 정렬 (변수를 지정하지 않아도 한번 수행하면 f에 할당되는 정렬)

# g = np.array([42,38,12,25])
# 정렬된 [12 25 38 42] 순으로 원래 데이터 g의 인덱스 번호 추출
# 인덱스 순서대로 원래 데이터 가져와서 정렬
# 내림차순

# 통계 수학 함수
# 합
# 평균
# 분산
# 표준편차
# 밑이 자연상수 e인 지수함수

# h1 = np.arange(1,5).reshape(2,2)
# h2 = np.arange(5,7).reshape(1,2)
# 출력 (2가지 방법씩)
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

# array([[1, 2, 5],
#        [3, 4, 6]])
# h1과 h2 내적 (2가지 방법)

# i = np.array([1,3,0], float)
# a>1 이 참이면 10, 거짓이면 0을 반환
# a>1 이 참인 경우 index 값을 반환

# j = np.array([np.Inf, np.NaN, 1, np.nan, np.inf, np.NAN])
# nan 개수

# k = np.array([1,2,4,5,8,78,23,3])
# 제일 큰 78의 인덱스값 반환 (최대값 반환)
# 제일 작은 1의 인덱스값 반환 (최소값)

# l = a.reshape(2, -1)
# 출력
# array([3, 1])
# array([0, 3])
# array([1, 1, 1, 0])
# array([0, 0, 0, 1])

# m = np.array([1,2,4,5,8,78,23,3])
# a가 4보다 큰 값만 나옴 (참인 값만 반환)

# n1 = np.array([2,4,6,8])
# n2 = np.array([1,3,2,0,0,1])
# n2 각 원소의 인덱스 값을 가진 n1 반환 (2가지 방법)

# o1 = np.arange(1,13).reshape(3,4)
# o2 = np.array([1,2,0,1])
# o3 = np.array([2,1,3,0])
# 매트릭스 , o2,o3 각 원소의 인덱스 값을 가진 o1 반환


# 사분위수
# 최소값
# 1사분위수
# 2사분위수
# 3사분위수
# 최대값

In [ ]:
import numpy as np

In [ ]:
# [1,4,5,8] 각 원소가 실수형인 배열 생성
# 원소의 타입과 몇 by 몇인지 확인

hw1 = np.array([1,4,5,8],dtype=float)
print(hw1)
print(type(hw1), hw1.shape)

[1. 4. 5. 8.]
<class 'numpy.ndarray'> (4,)

In [ ]:
# Vector (1차원) 생성 [1,2,3,4]
# Matrix (2차원) 생성 [[1,2,3],[4,5,6]]
# Tensor (3차원) 생성 [[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
#                     [[13,14,15,16],[17,18,19,20],[21,22,23,24]]]

vector = np.arange(1,5)
print(vector)

matrix = np.arange(1,7).reshape(2,3)
print(matrix)

tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

In [ ]:
# [1,2,3] 각 원소의 타입이 float32, int8 인 배열 각각 생성
hw2 = np.array([1,2,3],dtype=np.float32)
print(hw2)

hw3 = np.array([1,2,3], dtype=np.int8)
print(hw3)

[1. 2. 3.]
[1 2 3]

In [ ]:
# Matrix
# 1차원 벡터로 변경 (2가지 방법)
hw4 = matrix.reshape(-1,)
print(hw4)

hw5 = matrix.flatten()
print(hw5)

# (3 by 2) 2차원 매트릭스로 변경
hw6 = matrix.reshape(3,2)
print(hw6)

# 3 혹은 2만 사용해서 (3 by 2) 2차원 매트릭스로 변경
hw7 = matrix.reshape(3,-1)
hw8 = matrix.reshape(-1,2)
print(hw7)
print(hw8)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]

In [ ]:
# Matrix
# 원소 5를 추출
print(matrix[-1,1])

# Tensor
# 원소 19 추출
print(tensor[1,1,2])

5
19

In [ ]:
a = np.arange(16).reshape(4,-1)
print(a)

# 결과값
# [[5,6],
#  [9,10]]

# [[5,6,7],
#  [9,10,11]]

# [[1,3],
#  [9,11]]

print(a[1:3,1:3])
print(a[1:3,1:])
print(a[0::2,1::2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  6]
 [ 9 10]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 1  3]
 [ 9 11]]

In [ ]:
# x 는 앞에 3열
# y 는 마지막 열
# shape로 결과값을 보면
# x.shape ==> (4,3)
# y.shape ==> (4,)

x = a[:-1,].reshape(4,3)
print(x)
print(x.shape)

y = a[-1,]
print(y)
print(y.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
[12 13 14 15]
(4,)

In [ ]:
# 배열 만들어서 다음 출력값이 나오게
# array([1, 3, 5, 7, 9])
# array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])
# 바로 윗줄 배열을 리스트 형태로 변환

hw9 = np.arange(1,10,2)
print(hw9)

hw10 = np.arange(0,5.1,0.5)
print(hw10)

[1 3 5 7 9]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]

In [ ]:
# -2부터 2까지 401등분한 배열 만들기

hw11 = np.linspace(-2,2,401)
print(len(hw11))

401

In [ ]:
# (2,4) 행렬을 1로 다 채우기 (정수형으로)
# (2,4) 행렬을 0으로 다 채우기 (실수형으로)

hw12 = np.ones((2,4), dtype=np.int8)
print(hw12)

hw13 = np.zeros((2,4), dtype=np.float32)
print(hw13)

[[1 1 1 1]
 [1 1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [ ]:
b = np.arange(12).reshape(3,4)
print(b)
# 원본 배열을 유지하면서 원소 값을 1로 다 바꾸기
# 원본 배열을 유지하면서 원소 값을 0으로 다 바꾸기

hw14 = np.ones_like(b)
hw15 = np.zeros_like(b)

print(hw14)
print(hw15)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

In [ ]:
# 대각선이 1인 3 by 3 정방행렬 만들기 (원소는 정수형으로) (2가지 방법)

hw16 = np.identity(3, dtype=np.int8)
print(hw16)

hw17 = np.eye(3,3, dtype=np.int8)
print(hw17)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]

In [ ]:
# 출력값
# array([[0, 0, 1, 0, 0],
#        [0, 0, 0, 1, 0],
#        [0, 0, 0, 0, 1]], dtype=int32)

hw18 = np.eye(3,5,k=2,dtype=np.int8)
print(hw18)

# array([[0., 0., 0.],
#        [1., 0., 0.],
#        [0., 1., 0.],
#        [0., 0., 1.]])

hw19 = np.eye(4,3,k=-1,dtype=np.float32)
print(hw19)

[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [ ]:
# c = np.arange(9).reshape(3,3)
# 대각선 위치의 값을 추출 array([0, 4, 8])
# array([1, 5])

# np.random.seed(seed=1000) # 시드로 난수 생성 초기값 지정
# np.random.uniform(0, 1, 10).reshape(2,5) # 균등 분포 # 최소 최대 개수
# np.random.normal(0, 1, 10).reshape(2,5) # 정규 분포 # 평균 표준편차 개수
# np.random.binomial(n, p, size) # 이항 분포
# np.random.poisson(lam. size) np # 포아송 분포
# np.random.standard_t(df, size) np # t-분포
# np.random.f(dfnum, dfden, size) # F-분포

# d = np.arange(1,13).reshape(3,4)
# 모든 원소의 합
# 모든 행들의 합 array([10, 26, 42])
# 모든 열들의 합 array([15, 18, 21, 24])

# e = np.arange(1, 25).reshape(2,3,4)
# 모든 원소의 합
# array([[14, 16, 18, 20],
#        [22, 24, 26, 28],
#        [30, 32, 34, 36]])
# array([[15, 18, 21, 24],
#        [51, 54, 57, 60]])
# array([[10, 26, 42],
#        [58, 74, 90]])

# f = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
# 정렬 (자기 자신 바뀌지 않는 버전)
# array([[ 3,  4,  5,  7],
#        [ 1,  9, 11, 12],
#        [ 1,  2,  5, 14]])

# array([[ 1,  3,  1,  7],
#        [ 2,  5,  5,  9],
#        [ 4, 12, 11, 14]])

# 정렬 (변수를 지정하지 않아도 한번 수행하면 f에 할당되는 정렬)

# g = np.array([42,38,12,25])
# 정렬된 [12 25 38 42] 순으로 원래 데이터 g의 인덱스 번호 추출
# 인덱스 순서대로 원래 데이터 가져와서 정렬
# 내림차순

# 통계 수학 함수
# 합
# 평균
# 분산
# 표준편차
# 밑이 자연상수 e인 지수함수

# h1 = np.arange(1,5).reshape(2,2)
# h2 = np.arange(5,7).reshape(1,2)
# 출력 (2가지 방법씩)
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

# array([[1, 2, 5],
#        [3, 4, 6]])
# h1과 h2 내적 (2가지 방법)

# i = np.array([1,3,0], float)
# a>1 이 참이면 10, 거짓이면 0을 반환
# a>1 이 참인 경우 index 값을 반환

# j = np.array([np.Inf, np.NaN, 1, np.nan, np.inf, np.NAN])
# nan 개수

# k = np.array([1,2,4,5,8,78,23,3])
# 제일 큰 78의 인덱스값 반환 (최대값 반환)
# 제일 작은 1의 인덱스값 반환 (최소값)

# l = a.reshape(2, -1)
# 출력
# array([3, 1])
# array([0, 3])
# array([1, 1, 1, 0])
# array([0, 0, 0, 1])

# m = np.array([1,2,4,5,8,78,23,3])
# a가 4보다 큰 값만 나옴 (참인 값만 반환)

# n1 = np.array([2,4,6,8])
# n2 = np.array([1,3,2,0,0,1])
# n2 각 원소의 인덱스 값을 가진 n1 반환 (2가지 방법)

# o1 = np.arange(1,13).reshape(3,4)
# o2 = np.array([1,2,0,1])
# o3 = np.array([2,1,3,0])
# 매트릭스 , o2,o3 각 원소의 인덱스 값을 가진 o1 반환


# 사분위수
# 최소값
# 1사분위수
# 2사분위수
# 3사분위수
# 최대값

# 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
# 10 20 30 40
# 50 60 70 80

# m2 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9],[10, 11, 12, 13, 14]])
# 1) 이 행렬에서 값 7 을 인덱싱한다. 
# 2) 이 행렬에서 값 14 을 인덱싱한다.
# 3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
# 4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
# 5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

#2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
# 1) 이 배열에서 3의 배수를 찾아라.
# 2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
# 3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

# 값을 직접 입력하지 말고
# 우측의 행렬을 만드시오.
# 2, 1, 0, 0, 0
# 3, 2, 1, 0, 0
# 0, 3, 2, 1, 0
# 0, 0, 3, 2, 1
# 0, 0, 0, 3, 2

# 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에
# 대해 다음과 같은 값을 구하시오.
# 1) 전체의 최댓값
# 2) 각 행의 합
# 3) 각 행의 최댓값
# 4) 각 열의 평균
# 5) 각 열의 최솟값

# 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은
# 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.
# array([[ 1,   2,   3,  4],
#        [ 46, 99, 100, 71],
#        [ 81, 59, 90, 100]])
# 결과값 
# [[  3   2   4   1]
#  [100  99  71  46]
#  [ 90  59 100  81]]

# 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고,
# 던져서 나오는 숫자의 평균을 구하시오.

# 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고
# 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.

# Pandas

In [ ]:
import pandas as pd
import numpy as np


dict_data = {"a":1, "b":2, "c":3}
# 딕셔너리를 시리즈 형태로 변환
# 인덱스와 값 확인

list_data = ['영인','2010-05-01', '여', 14, True]
# 리스트를 시리즈 형태로 변환
# 인덱스는 '이름','생년월일','성별', 나이, '학생여부' 로 지정
# 여 인덱싱 (2가지 방법)
# 여러개 원소 영인, 14 인덱싱 (2가지 방법)

# 시리즈 만들기
# 서울 9904312
# 부산 3448737
# 인천 2890451
# 대구 2466052

# 3448737 만 인덱싱 (2가지 방법)
# 3448737 와
# 2466052 두개 인덱싱 (2가지 방법)

import seaborn as sns
iris = sns.load_dataset('iris')

# 각 열의 원소 개수 확인
# species 열의 종류 확인
# species 열의 종류별 값 개수 확인

# sr = pd.Series([9904312,3448737,2890451,2466052], index=["서울","부산","인천","대구"])
# 데이터의 전체 합 구하기
# 데이터의 전체 평균 구하기
# 오름차순 정렬
# 내림차순 정렬

dict_data = {'c0':[1,2,3],'c1':[4,5,6],'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,15]}
# 딕셔너리를 데이터프레임 형태로 변환

list_data=[[15,'남','신촌중'],[17,'여','연세중']]
# 리스트를 데이터프레임 형태로 변환
# 인덱스는 준서 예은
# 열 이름은 나이 성별 학교
# 인덱스 이름과 열 이름 확인하기
# 인덱스 학생1 학생2 로 변경
# 열 이름 연령 남여 소속 으로 변경
# 메소드를 사용해서 행과 열이름 변경
# 인덱스 학생1을 학생3으로
# 열이름 소속을 비고로

# numpy random.randint를 사용해서 60~100 사이 16개 숫자를 만들고
# reshape하고 index가 james, maria, brian, alice를 만들고
# 컬럼이름은 kor, eng, math, music로 된 데이터 프레임을 생성하기

# 변수 복사하기 (2가지 방법)

# brian 행 삭제
# james, maria 행 한번에 삭제

# eng 열 삭제
# kor, music 열 한번에 삭제

# 원본 데이터에서 maria 행 뽑아오기 (2가지 방법)
# brian과 alice 행 한번에 뽑아오기 (2가지 방법)
# maria와 brian 슬라이싱으로 행 뽑아오기 (2가지 방법)

# math 열 뽑아오기
# math와 music 열 뽑아오기
# math 열만 뽑되, 데이터프레임 형식으로 뽑기

# maria 음악점수 가져오기 (2가지 방법)
# james의 영어 수학 음악점수 가져오기 (2가지 방법)
# 마리아~엘리스 영어~음악까지 가져오기 (2가지 방법)

# gym 열 추가하고 값은 90으로 통일
# gildong 행 추가하고 값은 90,70,60,75,60으로

# 인덱스 순서를 James maria gildong brian alice 순으로 변경

# exam_data = {'이름':['길동','철수','영희'], '수학':[90, 80, 70],
#             '영어':[98,89,95], '음악':[85,95,100], '체육':[100,90,90]}
# df = pd.DataFrame(exam_data)
# 이름을 인덱스로 지정
# 인덱스로 지정된 이름을 열로 변환

# dict_data = {'c0':[1,2,3],'c1':[4,5,6],'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,15]}
# df = pd.DataFrame(dict_data, index=['r0','r1','r2'])
# 인덱스를 r0 r1 r2 r3 r4로 새로 지정해서 행 추가 후 값은 0으로 채우기
# 행 인덱스 내림차순 정렬
# 열 c1 기준으로 내림차순 정렬

# student1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
# student2 = pd.Series({'수학':80,'국어':90,'영어':80})
# np.nan 결측값을 0으로 처리해서 사칙 연산 + - * /

# import seaborn as sns
# titanic = sns.load_dataset('titanic')
# 열 age fare만 뽑기

# csv 파일 만들기
# %%writefile sample.csv
# c1,c2,c3
# 1,1.15,one
# 2,2.23,two
# 3,3.32,three

# csv 파일 불러오기 (excel, json, html 등 같은 구조)
# c1 c2 c3 가 열 이름이 아닌 첫번째 행으로 되게 불러오기
# 1,1.15,one 가 열이름, 첫번쨰 행 2,2.23,two 으로 되게 불러오기
# c1을 인덱스로 잡히게 불러오기
# 데이터를 csv로 저장 (excel, json, html 등 같은 구조)

# mpg.csv 불러오기 (열 이름 없는 구조 주의)
# df.columns = ['mpg', 'cylinders', 'displacement','horsepower','weight',
#               'acceleration','model year', 'origin', 'name']

# 첫 5개 행 출력
# 끝 5개 행 출력
# 행의 개수와 열의 개수 확인
# 데이터의 정보 확인 (열이름, 결측값 아닌 값 개수, 타입 등 한번에 나오는것)
# 데이터프레임 기술통계 정보 확인
# 각 열이 가지고 있는 값의 개수 확인
# origin 열의 종류 확인
# origin 열의 종류별 값 개수 확인

# mpg 열의 평균, 중앙값, 최소값, 최대값, 표준편차 각각 구하기

# 데이터의 상관계수 한번에 확인
# 특정 열 mpg 와 weight의 상관계수 확인

# 남북한발전전력량.xlsx 불러오기
# 1990년도부터 남한과 북한의 합계 행 2개만 가져오기
# 행 인덱스를 south와 north로 변경
# 열 이름을 정수형으로 변경
# 행과 열 서로 바꾸기
# 그래프 그리기
# 막대그래프로 그리기

# 시각화

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# mpg 데이터 불러오기
# df.columns = ['mpg', 'cylinders', 'displacement','horsepower','weight',
#               'acceleration','model year', 'origin', 'name']

# 기본 내장 시각화
# mpg와 cylinders 의 boxplot
# 히스토그램 그리기
# 구간 = 10, 색 지정, 그림 사이즈 10,5

# 산점도 scatter 그리기
# x축 weight, y축 mpg / 색 지정, 사이즈 10, 그림사이즈 10,5
# 차트 제목 'scatter plot mpg VS. weight'

# 버블차트 그리기
# 버블차트를 그리기 위해 cylinder 개수의 상대적 비율을 계산하여 시리즈 생성
# 산점도 그리기 (cylinder 크기 이용), 투명도 0.3
# 차트 제목 'scatter plot : mpg-weight-cylinders'

# 3개의 변수로 산점도 그리기
# 산점도 그리기 (cylinder 크기 이용), 투명도 0.3, 크기 50
# +마커, 오른쪽 네모 박스 색 지정

# count열 추가 : 값은 1
# origin 고유의 값의 합만 뽑기 (origin별로 각 열의 합 구하기)
# 새로운 데이터프레임으로 만들고 인덱스는 'USA', 'EU', 'JAPAN'로 지정

# count열의 파이 차트 그리기
# 그림사이즈 7,5, 값 표시는 소수점 첫째자리 %로 표시
# 파이조각을 나는 시작 점 (각도 표시) 10
# 색 지정
# 차트 제목 'Model origin', 크기 20
# 파이 차트의 비율을 같게(원에 가깝게) 조정 (원의 형태를 유지할 수 있도록)
# 범례는 인덱스가 표시되게, 위치는 오른쪽 위에

# box plot
# 그림 사이즈 가로 15인치, 세로 5인치 지정
# 2개 그래프 그리기
# 1. origin 별로 mpg 박스플롯
# 2. 박스플롯 옆으로 그리기
# 차트 제목 1. 제조국가별 연비분포(수직박스) / 2. 제조국가별 연비분포(수평박스)

# 시도별 전출입 인구수 데이터 불러오기
# engine = "openpyxl"
# 행 열의 개수, 정보, 기술통계 확인
# 결측값 앞의 값으로 채워넣기

# 서울에서 다른 지역으로 이동한 데이터만 추출
# 전출지별 열 삭제
# 전입지별 -> 전입지로 열이름 변경
# 전입지 열을 인덱스로 지정

# 서울에서 경기도로 이동한 인구 데이터 값만 선택

# 해당 데이터 그래프
# matplotlib 이용한 간단한 그래프 그리기
# 그림 사이즈 가로 12인치, 세로 6인치 지정
# 동그란 마커, 사이즈 10으로 그래프 그리기
# 차트 제목 추가 '서울 -> 경기 인구 이동'
# 축의 이름 지정하고 크기는 10으로
# x축 - 기간 / y축 - 이동인구수
# x축 눈금라벨 사이즈 10, 90도 회전
# y축 범위 5000~800000
# 범례 : '서울 -> 경기' 글씨 사이즈 25, 최적의 위치
# 주석 표시
# 주석 1 : "인구이동증가(1970-1995)" , 위치 기준점 10, 400000, 크기 20
# 주석 2 : "인구이동감소(1995-2017)" , 위치 기준점 40, 400000, 크기 20
# 변경사항을 저장하고 그래프로 출력

# 그림 사이즈 가로 10인치, 세로 10인치 지정
# 2개 그래프 그리기
# 1. 동그란 마커, 사이즈 10
# 2. 세모난 마커, 마커 색 그린, 사이즈 15, 선 색 올리브, 
# 선 굵기 4, 범례에 표시되는 서울-> 경기
# 범례 위치 최적
# 2개 그래프 y축 범위 지정 50000~800000
# x축 내용 표시, 75도 회전

# 서울에서 '충청남도', '경상북도', '강원도', '전라남도'로 이동한 인구데이터 값만 선택
# 그래프 테마 ggplot으로 지정
# 그림 사이즈 가로 20인치, 세로 5인치 지정
# 한 도화지에 4개 그래프 겹쳐서 그리기
# 동그란 마커, 크기 10, 선 굵기 2, 색 지정, 범례에 표시되는 서울 -> 00
# 범례 최적의 위치에 나오게
# 그래프 제목 '서울->충남, 경북, 강원, 전남 인구이동', 크기 20
# x축 - 기간 / y축 - 이동인구수
# x축 눈금라벨 90도 회전

# 그림 사이즈 가로 20인치, 세로 10인치 지정
# 4등분 해서 각자 한개씩 나오게

# 데이터 행과 열 서로 바꾸기
# 인덱스를 정수형으로 변경
# 면적그래프 그리기
# 선 그래프 누적되지 않고 서로 겹치도록, 투명도 0.2, 그림사이즈 20,10
# 그래프 제목 '서울 -> 타도시인구이동' 크기 25
# x축 - 기간 / y축 - 이동인구수 크기 15
# 범례 최적의 위치, 크기 15

# bar 그래프
# 그림 사이즈 20, 10 / 막대 사이 공간 0.7 / 색 지정
# 그래프 제목 '서울 -> 타도시인구이동' 크기 25
# x축 - 기간 / y축 - 이동인구수 크기 15
# 범례 최적의 위치, 크기 15

# 데이터 행과 열 서로 바꾸기
# 합계 열 만들기 (값은 행의 합)
# 합계의 가장 큰 값부터 정렬

# barh 그래프
# 그림 사이즈 10, 5 / 막대 사이 공간 0.5 / 색 지정
# 그래프 제목 '서울 -> 타도시인구이동' 크기 20
# x축 - 이동인구수 / y축 - 전입지 크기 15

# 남북한발전전력량 데이터 불러오기
# 북한 데이터만 가져오기
# 인덱스를 발전 전력별로 변경
# 행과 열 서로 바꾸기
# 열이름 변경 / 합계 -> 총발전량
# 총발전량(전년) 열 추가 , 값은 전년도 총발전량
# 증감율 열 추가, 값은 계산 (파생변수)

# 2축 그래프 그리기
# 1. 수력, 화력 누적해서 그림사이즈 20,10 / 사이공간 0.7 인 bar그래프 그리기
# 2. x 인덱스, y 증감율 그래프 그리기
# 선 스타일 --, 동그란 마커, 크기 20, 색 그린, 범례 표시 "전년대비 증감율"
# 1. x축 - 연도 , y축 - 발전량(억 Kwh)
# 2. y축 - 전년대비 증감율
# 범례 위치 : 왼쪽 상단

# Seaborn
# 타이타닉 데이터 불러오기

# regplot
# 그림 사이즈 15,5
# 2개 그래프 그리기 x-age / y=fare
# 1. 선형 회귀선 표시
# 2. 선형 회귀선 미표시

# scatter
# 그림 사이즈 15,5
# 2개 그래프 그리기 x-class / y=fare
# 1. 데이터의 분산 미고려
# 2. 데이터의 분산 고려 (중복X)

# bar plot
# 그림 사이즈 15,5
# 3개 그래프 그리기 x-sex / y=survived
# 1. 기본
# 2. class 별로 쪼개기
# 3. class 별로 쪼개되 누적으로 보이게

# count plot - 빈도 그래프
# 그림 사이즈 15,5
# 3개 그래프 그리기 x-class
# 1. 기본
# 2. who 별로 쪼개기
# 3. who 별로 쪼개되 누적으로 보이게

# boxplot
# 그림 사이즈 15,5
# 2개 그래프 그리기 x-alive, y-age
# 1. 기본
# 2. sex 별로 쪼개기

# violinplot - 바이올린그래프
# 그림 사이즈 15,5
# 2개 그래프 그리기 x-alive, y-age
# 1. 기본
# 2. sex 별로 쪼개기

# join plot : 산점도 + 히스토그램
# 그림 사이즈 15,10
# 4개 그래프 그리기 x-fare, y-age
# 1. 기본
# 2. 회귀선
# 3. 육각 산점도
# 4. 커널 밀집 그래프

# flights 데이터 불러오기
# 행 month 열 year 값 passengers 로 피벗 돌리기
# 그림 사이즈 10,8
# 차트 제목 '연도, 월별 승객수에 대한 Heatmap'

# 히트맵 그리기
# 각 셀의 값 표기
# 값의 데이터 형태 정수형
# 셀 사이 선 굵기 1

# iris 데이터 불러오기
# 관계그래프 그리기
# species 별로 쪼개기

# import folium
# 서울 위도, 경도 37.55, 126.98
# 서울지도 만들기
# 지도를 HTML 파일로 저장

# 서울지역 대학교 위치 데이터 불러오기, 인덱스 지정
# 대학교 리스트를 데이터프레임으로 전환
# 서울 지도 만들기
# 서울 지도에 대학교 명, 위도, 경도 마커 추가하기, 팝업에는 대학교명

# 서울 지도2 만들기
# 동그란 마커 추가하기
# 둘레 10, 둘레 색 갈색, 안에 채우기, 안의 원 코랄색, 투명도 0.7, 팝업에는 대학교명

# 경기도 인구변화 데이터를 불러와서 데이터 프레임으로 변환
# 경기도 시군구 경계 정보를 가진 geo-json 파일 불러오기
# 경기도 지도 만들기
# 출력할 연도를 선택(2007~2017)
# 단계구분도(Choropleth) 단계구분도 표시하기
# 지도를 Html로 저장

# 데이터 전처리

In [ ]:
# seaborn dataset에서 타이타닉 불러오기
# 각 열마다 결측값 개수 합 구하기
# deck 열 고유의 값 구하기
# deck 열의 고유의 값별로 개수 확인하기 (결측치 순위 포함)
# 각 행마다 결측치가 아닌 값의 개수 확인하기
# Nan 값이 500개 이상인 열을 모두 삭제 - deck열(891개중 688개 Nan) 삭제

# age 열에 나이데이터 없는 모든 행을 삭제
# age 열의 Nan값을 다른 나이 데이터의 평균으로 변경
# embark_town 승선지는 Nan값을 최빈값(가장 많이 출연한 값)으로 채우기
# embarked 열의 Nan 값을 바로 앞에 있는 값으로 변경하기

# df2 = pd.DataFrame({'c1' : ['a','a','b','a','b'],
#                     'c2' : [1,1,1,2,2],
#                     'c3' : [1,1,2,2,2]})

# 중복 데이터 찾기
# 데이터 프레임의 특정열에서 데이터 중복 값을 찾기 ('c2')
# 데이터프레임에서 중복 행 제거
# 데이터 프레임의 특정열 기준으로 데이터 중복 행 제거 ('c2')

df = pd.read_csv('./auto-mpg.csv', header = None)
df.columns = ['mpg', 'cylinders', 'displacement','horsepower','weight',
              'acceleration','model year', 'origin', 'name']
mpg_to_kpl = 1.60934 / 3.78541

# mpg 열에 mpg_to_kpl(0.425)를 곱해서 새로운 kpl 컬럼을 생성 (파생변수)
# kpl 열을 소수점 아래 둘째자리 반올림
# 각 열의 자료형 확인
# horsepower의 고유값 확인
# 누락데이터('?')를 결측값으로 처리하기
# horsepower 열에 결측값이 있는 행 다 지우기
# horsepower 데이터 타입을 실수형으로 변경

# origin 열의 고유값을 확인
# origin 값을 각각 'USA', 'JAPAN', 'EU' 로 변경
# origin 열의 자료형 확인
# origin 열의 문자열 자료형을 범주형 자료로 변환
# origin 열의 카테고리 자료형을 다시 변환
# model_year 정수를 범주형으로 변환
# model_year의 값을 랜덤 샘플로 3개 뽑기

# horsepower 열을 3개의 bin으로 나누는 경계 값의 리스트 구하기
# 3개의 구간에 이름 지정 -> '저출력','보통출력','고출력'
# 각 데이터를 3개의 bin에 할당
# hp_bin 열의 범주형 데이터를 더미변수로 변환 (원핫인코딩)

# stock-data 불러오기
# new_date 열에 Date 열을 Date형식의 자료형으로 변환
# new_date 열을 인덱스로 지정하고 Date열을 삭제

# dates=['2019-01-01','2020-03-01','2021-06-01']
# dates를 Date형식의 자료형으로 변환
# Timestamp를 각각의 period로 변환 (일, 월, 년)

# Timestamp의 배열 만들기
# 2019.01.01 날짜범위 시작, timestamp의 개수=6
# 월간격, 월의 시작일 기준
# 월 간격, 월의 마지막 날 기준
# 분기(3개월) 간격, 월의 마지막날 기준

# 타이타닉 데이터에서 age와 fare열 가져오기
# add_10 함수 만들기 (10을 더해주는 함수)
# age와 fare 열에 함수를 이용해 10을 더한 값으로 변경
# missing_value 함수 만들기 (시리즈 형태 집어넣으면 결측값 True/False값 반환)
# result 변수에 age와 fare 열의 결측값 True/False 반환값 넣기
# min_max 함수만들기 (가장 큰 수에서 가장 작은 수 뺀 값 반환)
# result2 변수에 age와 fare 열의 최대값에서 최소값 뺀 값 넣기

# ten 열 만들기 , 값은 10
# add_two_obj 함수 만들기 (두 값을 더한 값 반환)
# add 열 추가 , 값은 각 행의 age열과 fare 값을 더한 값

# filename = '서울시CCTV설치운영현황(자치구)_년도별_211231기준.csv'
# cctv 데이터 불러오기
# 총계 열의 값을 정수형으로 변환
# 결측치를 0으로 대체
# 모든 열의 값을  정수형으로 변환

# 타이타닉 데이터
# 1. age 결측값을 평균으로 대체
# 2. embarked  최빈값으로 대체
# 3. embark_town 결측값이 있는 행 삭제
# 4. deck 삭제
# 5. titanic['adult/child'] 컬럼을 만들고 20살 이상이면 adult 이하면 child (apply, lambda 활용)
# 6. bins = [1, 20, 30, 50, 70, 100]
#    labels = ['미성년자', '청년', '중년', '장년', '노년']
# age를 기준으로 'age_cut' 컬럼을 생성후 두 컬럼을 출력하기
# age, age_cut
# 22   청년
# 38   중년
# pd.cut()

# 데이터 프레임 연결
# df1 = pd.DataFrame([['a',1],['b',2]],columns=['letter', 'number'])
# df2 = pd.DataFrame([['c',3],['d',4]],columns=['letter', 'number'])
# df3 = pd.DataFrame([['e',5,'!'],['f',6,'@']],columns=['letter', 'number','etc'])\

# 컬럼명을 기준으로 연결
# 공통된 컬럼만 남기기
# 인덱스 재지정

# 열로 연결하기
# df4 = pd.DataFrame({'age':[20,21,22]}, index=['amy','james','david'])
# df5 = pd.DataFrame({'phone':['010-1111-1111',
#                              '010-2222-2222',
#                              '010-3333-3333']},
#                    index=['amy','james','david'])
# df6 = pd.DataFrame({'job':['student','programer','ceo','designer']},
#                    index=['amy','james','david', 'kim'])

# 인덱스를 기준으로 연결
# 공통된 인덱스만 남기기

# df = pd.read_csv('scores.csv')
# df7 = df의 인덱스 1,2,3 컬럼 name, eng
# df8 = df의 인덱스 1,2,4 컬럼 name, math

# 공통 데이터만으로 연결
# 모두 다 합치기
# df7 기준으로 연결
# df8 기준으로 연결

# df 데이터 재구조화
# name을 고정하여 재구조화
# name과 kor을 고정하여 재구조화
# 행으로 위치를 변경할 열 지정 (kor)
# 행으로 위치를 변경할 열 지정 (kor, eng) , 구분 - subject, 값 - score 열이름 지정

# df = name 고정, 구분 - subject, 값 - score 열이름 지정
# get_grade 함수 만들기
# x 90이상 A, 80 B, 70 C, 60 D, 그 외 F
# grade 열 추가 (점수에 등급 함수 적용)
# name 열 이름 순으로 정렬

#
# subject	eng 	kor	    math
# name
# Aiden 	90.0	100.0	95.0
# Amy	    75.0	90.0	90.0

# subject	eng	kor	math
# name
# Aiden	    A	A	A
# Amy	    C	A	A

# 	        score	        grade
# subject	eng	kor	math	eng	kor	math
# name
# Aiden	90.0	100.0	95.0	A	A	A
# Amy	75.0	90.0	90.0	C	A	A

# df = pd.DataFrame({"item": ["shirts", "shirts", "shirts", "shirts", "shirts",
#                           "pants", "pants", "pants", "pants"],
#                     "color": ["white", "white", "white", "black", "black",
#                           "white", "white", "black", "black"],
#                    "size": ["small", "large", "large", "small",
#                           "small", "large", "small", "small",
#                          "large"],
#                    "sale": [1, 2, 2, 3, 3, 4, 5, 6, 7],
#                    "inventory": [2, 4, 5, 5, 6, 6, 8, 9, 9]})
# df

# size	    large	small
# item
# pants	    15      17
# shirts	 9	    13

# 집계분석 item, size 별 재고 합계
# 	        size	large	small
# item	    color
# pants	    black	9.0	    9.0
#           white	6.0 	8.0
# shirts	black	NaN 	11.0
#           white	9.0	    2.0

# 'item','color', size별 재고와 판매 합계
# nan값에 0 넣기
# 		inventory	sale
# size	large	small	large	small
# item	color
# pants	black	9	9	7	6
# white	6	8	4	5
# shirts	black	0	11	0	6
# white	9	2	4	1

# 타이타닉 데이터에서 'survived','pclass','sex','age','embarked' 열만 불러오기
# 결측값 있는 행 다 삭제

# 성별, 객실등급별 승선자수
# 성별, 객실등급별 생존자수
# 성별, 객실등급별 생존율
# 총합 나오게 명칭은 계

# tips = sns.load_dataset('tips')
# tip_pct 열 추가 (tip / total_bill) 퍼센트 소수점 둘째자리까지만

# smoker	Yes	No	계
# sex
# Male  	60	97	157
# Female	33	54	87
# 계     	93	151	244

# 	        tip_pct
# sex
# Male	    15.764713
# Female	16.648276

# 	    	tip_pct
# sex   	smoker
# Male	    Yes	15.276667
#            No	16.066598
# Female	Yes	18.214545
#            No	15.691111

# 	      mean	    min	    max
#       tip_pct	tip_pct	tip_pct
# smoker
# Yes	16.319140	3.56	71.03
# No	15.932318	5.68	29.20
# All	16.079754	3.56	71.03

# 타이타닉 데이터에서 'survived','pclass','sex','age','embarked' 열만 불러오기
# 객실등급(pclass) 별 승선자수 결과 집계
# 객실등급(pclass) 별 생존자수 결과 집계
# 객실등급(pclass) 별 생존비율 결과 집계
# 각 3개의 열 합치기

# 실습

In [ ]:
import pandas as pd
import numpy as np
from matplotlib import font_manager, rc 
import matplotlib.pyplot as plt
import matplotlib as mpl

#마이너스 표시
mpl.rcParams['axes.unicode_minus'] = False
plt.rc('font', family='Malgun Gothic')

In [1]:
### 실습 1 ###

# 서울시 코로나19 확진자 현황 데이터 불러오기
# '환자번호','국적','환자정보','조치사항',
# '이동경로','등록일','수정일','노출여부' 열 삭제
# 확진일 -> 날짜와 시간 자료 형태로 변경
# 지역 고유의 값, 개수 확인
# 지역 열의 공백 제거
# 지역 열을 범주형 자료로 변경
# df의 열별 결측값 확인

# 확진일 지역별로 집계 (pivot_table 이용)
# 행 확진일 / 열 지역 / 합계 나오게

# s_date 변수 - 서울시 확진일별 확진자
# 일별 확진자 많은 순으로 정렬해보기 (변수에 적용X)

# 그래프 제목 서울시 일별 확진자 시각화
# x축 이름 확진일 , y축 이름 확진자수
# x축라벨 45도 회전

# s_gu 변수 - 서울시 지역별 확진자
# 지역별 확진자 많은 순으로 정렬 (변수에 적용)

# 그래프 제목 서울시 구별 누적 확진자 시각화
# 그래프 사이즈 (5,4)
# 가로 막대그래프
# x축 이름 확진일 , y축 이름 확진자수

# 접촉력에 따른 확진 분석
# 접촉력열의 고유의 값, 개수 확인
# 접촉력 값 많은 순 10개
# 최근 월(2021 - 9월달만) 접촉력에 따른 확진건수 best10


### 실습 2 ###

# 공공자전거 대여이력 정보_2021.01 ~ 2021.06 데이터 각각 불러오기
# 데이터 연결하기
# '자전거번호','대여거치대','반납거치대' 열 제거
# 범주형변환 : '대여 대여소번호', '반납대여소번호'
# '대여일시', '반납일시' 날짜와 시간 자료 형태로 변경
# df의 열별 결측값 확인
# 결측치 있는 행 제거

# 대여날짜 컬럼을 추가 : 대여일시에 날짜만 불러오기
# 대여날짜별 대여 건수 : 집계 (그룹분석) groupby 이용
#   대여날짜     대여일시
# 2021-01-01	22119
# 2021-01-02	23463
# 2021-01-03	21656
# 대여일시 컬럼명 대여건수로 변경
# 그래프 그리기

# 대여 날짜별 이용시간 groupby 사용 (df_time)
# 그래프 그리기
# 대여 날짜별 이용 거리 (df_distance)
# 그래프 그리기
# 데이터프레임 합치기
# 이용시간 + 이용거리 + 대여건수

# 시간대별 대여/반납 현황
# 대여시간 열 추가, 대여일시의 시만 뽑기
# 반납시간 열 추가, 반납일시의 시만 뽑기
# 시간대별 대여 현황 (df_rental)
# 시간대별 반납 현황 (df_return)

# 시간대별 대여건수 막대그래프 그리기
# x축 이름 - 대여시간, y축 이름 - 대여건수

# 시간대별 반납건수 막대그래프 그리기 (색 - 코랄)
# x축 이름 - 반납시간, y축 이름 - 반납건수

# 대여소별 대여/반납현황
# 반납대여소번호 0을 제거
# 문자열로 변환 -> 왼쪽의 0을 제거 -> 정수형 변환 -> 범주형 자료로 변환

# 대여건수가 많은 대여소 best 10
# 반납건수가 많은 대여소 best 10

# 여의나루역 1번출구 앞 대여소 이용 현황
# 대여 대여소번호가 207인것만 df_207 변수에 넣기
# 빌린곳에서 반납한 자전거의 날짜별 이용시간
# 여의나루 1번출구앞에서 빌려서 제일 많이 반납한 장소

# 대여요일 열 추가 : 대여일시에서 축약된 요일명으로 불러오기
# 무슨 요일에 가장 많이 빌리는가

# df_207 기본통계 이용시간 (평균, 최대, 최소값)
# 전체데이터의 평균

### 실습 3 ###
# 생필품 농수축산물 가격 정보(2021년1월_6월) 불러오기
# 시장/마트 번호 고유의 값, 개수 확인
# 시장/마트 이름 고유의 값, 개수 확인

# 시장/마트 목록 만들기 (df_market)
# '시장/마트 번호','시장/마트 이름','자치구 이름','시장유형 구분(시장/마트) 이름' 열만
# 중복된 값 제거
# 자치구별 시장/마트 개수
# 자치구 이름이 중구인 시장/마트 목록

# 품목 목록 만들기 (df_items)
# '품목 번호','품목 이름' 열만
# 중복된 값 제거 , 30개씩 끊어서 전체 보기

# 자치구 목록 만들기 (df_gu)
# '자치구 코드','자치구 이름' 열만
# 중복된 값 제거

# 삼겹살 가격 분석
# 품목 이름 중에서 삼겹살이 포함된 행 가져오기
# 2021년 2021-06 데이터
# 600g 인것
# df_sam

# 가격의 평균
# 최대값 최저가
# 조건 : 5000원 이하인 시장/마트이름

# 구이름을 입력받아서
# 해당 구의 '시장/마트 이름','품목 이름','실판매규격','가격(원)' 열을 반환해주기
# 중복된 값 제거

# 시장/마트 이름 과 가격(원) 시각화 (산점도)
# 그래프 제목 : 입력받은 구 삼겹살 가격

# 시장/마트이름 입력받아서 (백화점)
# 해당 마트의 '시장/마트 이름','품목 이름','실판매규격','가격(원)' 열을 반환해주기
# 중복된 값 제거

# 시장/마트 이름 과 가격(원) 시각화 (산점도)

# 달걀 분석
# 21년 6월 데이터
# 규격 : 30개짜리 기준 데이터 프레임만들기
# 30개 평균 가격, 최대 가격, 최소 가격, 6000원 이하 어디인지
# 동네 입력받아서 달걀가격 확인, 백화점 지점별 달걀 가격
# 시각화(산점도)

### 실습 4 ###

# 서울시 지하철 호선별 역별 시간대별 승하차 인원 정보 데이터 불러오기
# 사용월 열 문자열로 형변환
# 작업일자 열 제거

# 승차 / 하차 데이터로 나누기
# 공통컬럼 df1
# 승차컬럼 df2
# 하차컬럼 df3

# df2 컬럼명 승차인원 제거
# df3 컬럼명 하차인원 제거

# df1, df2 합치기 (df_in)
# df1, df3 합치기 (df_out)

# df_in_202108 / df_out_202108 변수에 사용월이 202108인 행 넣기
# 출근시간에 가장 많은 사람이 승차하는 역은 어디일까?(08시-09시)
# 출근시간에 가장 많은 사람이 하차하는 역은 어디일까?(09시-10시)
# 퇴근시간에 가장 많은 사람이 승차하는 역은 어디일까? (18시-19시)
# 퇴근시간에 가장 많은 사람이 하차하는 역은 어디일까? (19시-20시)

# df_gangnam_in = df_in_202108 에서 강남역 추출
# 데이터 재구조화
# 열이름 시간대, 승차건수로 변경
# 승차건수로 내림차순 정렬
# 시간대별 승차인원 시각화 하기

# df_gangnam_out = df_out_202108 에서 강남역 추출
# 데이터 재구조화
# 열이름 시간대, 하차건수로 변경
# 하차건수로 내림차순 정렬
# 시간대별 하차인원 시각화 하기

# df_in_202108 를 df_in_202108_agg 변수에 복사
# 지하철역 컬럼을 인덱스로 지정
# 불필요한 컬럼 '사용월', '호선명', '지하철역' 제거
# 행, 열 합계 각각 추가

# 시간대별 승차건수
# 막대그래프 시각화

# 지하철 역별 승차건수
# 막대그래프 시각화

# df_out_202108 를 df_out_202108_agg 변수에 복사
# 지하철역 컬럼을 인덱스로 지정
# 불필요한 컬럼 '사용월', '호선명', '지하철역' 제거
# 행, 열 합계 각각 추가

# 시간대별 하차건수
# 막대그래프 시각화

# 지하철 역별 하차건수
# 막대그래프 시각화

# API

In [ ]:
# 기본 코드
import pandas as pd
import numpy as np
import requests
from urllib.parse import quote
import json
import folium

import seaborn as sns
from matplotlib import font_manager, rc 
import matplotlib.pyplot as plt
import matplotlib as mpl

#마이너스 표시
mpl.rcParams['axes.unicode_minus'] = False
plt.rc('font', family='Malgun Gothic')

In [ ]:
### 행안부API ###

# filename 변수에 행안부API 파일이 있는 주소 넣기
# api_key에 행안부API 승인키 넣기
# api_key 글자수 세기 (43)

# 인터넷으로 무언가를 보내거나 가져올때 쓰는 패키지
# 한글을 주소에 입력시 자동 변환해주는 패키지 불러오기

# https://business.juso.go.kr/addrlink/addrLinkApi.do?currentPage=1&countPerPage=10&keyword=강남대로12길&confmKey=TESTJUSOGOKR&resultType=json
# confmKey=TESTJUSOGOKR&resultType=json

# base_url에 기본주소 넣기
# params1에 quote코드까지 넣기
# params2에 승인키 주소 넣기
# url 변수에 위 세개 변수 합쳐서 전체 주소 만들기

# result변수에 url주소를 넣으면 반환된 해당 내용 넣기
# result 변수 text 형태로 확인
# text 파일을 json 파일로 읽기

# roadAddr 인덱싱
# places = "종로구청 노원구청 송파구청 마포구청 양천구청"
# places 공백으로 구분하여 리스트로 반환하기
# for문으로 places의 주소를 반환해 해당 장소의 roadAddr를 반환해주는 리스트 만들기

# 공공기관 열에 places 들어가게, 도로명주소에 addr_list 들어가게 딕셔너리 형태로 만들고
# 데이터프레임으로 저장
# csv 파일로 저장

### 카카오API ###

# filename 변수에 카카오API 파일이 있는 주소 넣기
# api_key에 카카오API 승인키 넣기
# api_key 글자수 세기 (32)

# 인터넷으로 무언가를 보내거나 가져올때 쓰는 패키지
# 한글을 주소에 입력시 자동 변환해주는 패키지 불러오기


# https://dapi.kakao.com/v2/local/search/address.json\query=전북 삼성동 100"
# search_url에 json까지 넣기
# url에 search_url와 검색쿼리문 합치기

# result변수에 url주소를 넣으면 반환된 해당 내용 넣기
# headers={"Authorization": f'KakaoAK {api_key}'} 승인키 옵션 넣어서 json으로 받기 (result 변수)
# x, y 인덱싱
# lng 변수에 x 실수형으로
# lat 변수에 y 실수형

# 공공기관 csv 파일 불러오기 (df)
# for문으로 공공기관 별 위도 경도 리스트 만들기
# df에 위도 경도 열 추가

# 지도 만들기
# 시작지점 위도 평균과 , 경도 평균 , 12
# 지도 위에 동그라미 표시 
# 원 크기 300
# 동그라미 찍을 위치는 해당 행의 위도와 경도
# 팝업은 해당행의 도로명주소가 뜨게 , 최대 넓이 200
# 마우스 갖다대면 공공기관명 뜨게
# 원 둘레 색 red
# 원 채우기 색 #3186cc

# 시각화2

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import font_manager, rc 
import matplotlib.pyplot as plt
import matplotlib as mpl
import json
import folium
import re

#마이너스 표시
mpl.rcParams['axes.unicode_minus'] = False
plt.rc('font', family='Malgun Gothic')

In [ ]:
### 단계 구분도 ###

# older_population.csv 불러오기

# 동 단위 단계구분도
# seoul-dong.geojson 파일 json 형태로 열기
# 'features' 확인

# 지도 시작위치 [37.581, 126.986] 지도 크기 11
# 단계구분도 만들기 
# 색 채우기 BuPu
# 색의 범주 '노령인구'
# 제목 노령인구 (중앙, 글씨크기 20)
# 적용

# 구 단위 단계구분도
# df_gu 변수에 구열과 인구열 만들기
# seoul-gu-simple.json 파일 json 형태로 열기
# 'features' 확인

# 지도 시작위치 [37.581, 126.986] 지도 크기 11
# 단계구분도 만들기 
# 색 채우기 BuPu
# 색의 범주 '노령인구'
# 제목 노령인구 (중앙, 글씨크기 20)
# 적용

### 서울시 주요 공원현황 지도만들기 ###

# 서울시 주요 공원현황 데이터 불러오기
# 면적의 자료를 문자열로 바꾸고 '총 '(공백있음) 글자 제거하고 
# 여러 글자 있는 경우 공백으로 구분한 뒤 첫번째 수치만 가져오기 (변수 area에 넣기)
# 값이 nan, 휴양 인 경우 값을 0㎡로 바꾸기

# area값의 고유 값 확인
# ㎡m²㎥ 제거하고 실수형으로 바꾸기
# 반올림해서 정수형으로 바꾸기

## 공원 면적에 따라 분류 ##
# area_criteria = [-1, 10000, 1000000, 12000000]
# labels = ['소형', '중형', '대형'] (scale 변수)
# size_info = [3, 7, 15] (size 변수)

## 새로운 프레임 만들기 ##
# df = df[['공원명', '지역','X좌표(WGS84)', 'Y좌표(WGS84)']]
# 컬럼명 '공원명', '지역', '경도', '위도' 로 변경
# 면적, 분류, 크기 열 각각 area scale size 값 추가

# df 모든 열의 결측값 개수 확인
# 지역 값이 결측값인 행 확인
# 위도, 경도 값이 결측값인 행 확인

# 결측치 있는 행 다 제거
# 파일명이 '서울공원요약' csv로 저장 (인덱스X)

# 지도 만들기
# 시작지점 위도 평균과 , 경도 평균 , 11
# 지도 위에 동그라미 표시 
# 원 크기 : 각 행의 크기 값
# 동그라미 찍을 위치는 해당 행의 위도와 경도
# 마우스 갖다대면 공원명과 면적m2 뜨게
# 원 둘레 색 crimson
# 원 채우기 색 crimson

### '서울공원요약' 시각화 ###

# 서울공원요약 데이터 불러오기 (park 변수)
## 자치구별 공원면적과 공원수 구하기
#         	sum	 count
# 지역		
# 강남구	3626398 	7
# 강동구	1526390	  7
# 면적 합 , 공원 개수
# df 컬럼명 공원면적, 공원수로 변경
# 과천시 행 제거

## 구별 공원면적 비율 및 인당공원 면적비교
# 서울시 인구와 면적 데이터 불러오기 (txt 형식인데 데이터프레임으로 가져오기) - seoul_df 변수
# 첫번째 행 제거
# 행 개수 확인
# 지역 열을 인덱스로 지정
# 공원집계 데이터와 인구데이터를 합치기 (df와 seoul_df의 인구 면적 열만 합치기)

# 면적에 1000000 곱하기
# 인구에 쉼표 없애고 정수형으로 만들기
# 면적비율 열 만들기
# 인당면적 열 만들기

## 시각화
# 자치구별 공원 면적 비율
# barh로 / 오름차순 / 눈금 있게 / 그래프 사이즈 12,8
# 그래프 제목 - 자치구 공원면적비율(%) 크기 15

# # 인당 공원 면적
# barh로 / 오름차순 / 눈금 있게 / 그래프 사이즈 12,8
# 그래프 제목 - 자치구 공원면적비율(%) 크기 15

# 자치구별 공원 현황 - csv로 저장하기 (인덱스 포함)

## 자치구별 자치구 면적 대비 공원 면적 단계 구분도
# 자치구별 공원 현황 불러오기
# gu_geo_data 불러오기 (seoul-gu-simple.json)

## 1. 자치구별 자치구면적 대비 공원면적
# 공원 위치 화면 표시


## 1. 자치구별 자치구인구 대비 공원면적
# 공원 위치 화면 표시

# 실습

In [ ]:
import numpy as np
import pandas as pd
from glob import glob # 데이터 불러올때 한번에 불러올 수 있는 패키지
from tqdm.notebook import tqdm
from matplotlib import font_manager, rc 
import matplotlib.pyplot as plt
import matplotlib as mpl
from draw_map import drawKorea # workspace에 있어야함

#마이너스 표시
mpl.rcParams['axes.unicode_minus'] = False
plt.rc('font', family='Malgun Gothic')

In [ ]:
### 실습 5 - 커피상권분석 ###

## 커피지수 part_1
# 소상공인시장진흥공단_상가(상권)정보_서울 데이터 불러오기
# 업종중분류코드 : Q12 -> 카페/커피샵 만 추출
# df에서 '상호명', '지점명', '시도명', '시군구명' 컬럼만 가져오기

# 상호명에 스타벅스나 starbucks(대소문자 무시)가 들어간 행 찾기
# 지점명중 스타벅스지점명이 없는 데이터 검색 (결측값 말고)
# 커피빈 이디야 빽다방의 한/영문 같이 검색해서 cb, ed, bd 변수에 넣기
# 각 행의 개수 확인

# 전국 데이터에서 4개 매장 정보 추출
# starbucks coffeebean ediya paik 변수에 빈 데이터 프레임 만들기
# '상호명', '시도명','시군구명' 열이름
# 디렉토리내 데이터파일을 for문으로 전처리

# 각각 csv파일로 저장하되 인덱스는 넣지 말기

## 커피지수 part_2

# starbucks, coffeebean, ediya, paik 파일 불러오기
# get_ID 함수 만들기
# 해당 브랜드에 각각 get_ID 함수로 ID 열을 만들기
# 각 브랜드별 ID열의 고유의 값 개수 확인
# 스벅 191, 커피빈 92, 이디야 238, 빽다방 174

# 모든 단위 도시를 합치기
# starbucks만 있고, ediya / paik 가 없는 지역 찾기

# 브랜드별 지역별 매장수 계산
# ID 인덱스를 열로 바꾸고 상호명을 해당 브랜드 이름으로 각각 만들기
# 가장 많은 이디야 기준으로 합치기
# nan값 0으로 바꾸기
# 각 브랜드 열 정수형으로 바꾸기
# 커피지수열 만들기 (스타벅스 + 커피빈)/(이디야 + 빽다방)
# 커피지수.csv로 저장 (인덱스 저장 안되게)

## 시각화

# 커피지수 데이터 불러오기 (cf)
# draw_korea_raw(2021).xlsx 데이터 불러오기 (map_raw)
# map_raw를 행인덱스 열인덱스 값 3개의 열로만 나오게 바꾸기 (map)
# 인덱스를 열로 꺼내기
# 컬럼명을 y, x, ID로 바꾸기

# map 기준으로 데이터 붙히기
# 각 브랜드 열 정수형으로 바꾸기
# 커피지수로 카토그램 그리기
# 커피지수 Top10

In [ ]:
tmp_gu_dict = {'수원' : ['장안구','권선구','팔달구','영통구'],
               '성남' : ['수정구', '중원구', '분당구'],
               '안양' : ['만안구', '동안구'],
               '안산' : ['상록구', '단원구'],
               '고양' : ['덕양구', '일산동구', '일산서구'],
               '용인' : ['처인구', '기흥구', '수지구'],
               '청주' : ['상당구', '서원구', '흥덕구', '청원구'],
               '천안' : ['동남구', '서북구'],
               '전주' : ['완산구', '덕진구'],
               '포항' : ['남구', '북구'],
               '창원' : ['의창구', '성산구', '진해구', '마산합포구', '마산회원구']}

In [ ]:
metro_list = ['서울특별시', '부산광역시', '대구광역시', '인천광역시', 
              '대전광역시', '광주광역시', '울산광역시']

In [ ]:
def get_ID(df):
    si_name = [None] * len(df) # 없으면 0
    for i in df.index:
        if df['시도명'][i] in metro_list:
            if len(df['시군구명'][i]) == 2:
                # 서울 중구, 대전 서구
                si_name[i] = df['시도명'][i][:2] + ' ' + df['시군구명'][i]
            else : 
                # 서울 용산, 서울 서대문
                si_name[i] =  df['시도명'][i][:2] + ' ' + df['시군구명'][i][:-1]
        else :
            si_len = len(df['시군구명'][i].split())
            if si_len == 1:
                if df['시군구명'][i][:-1] == '고성':
                    if df['시도명'][i] == '강원도':
                        si_name[i] = '고성(강원)'
                    else :
                        si_name[i] = '고성(경남)'
                elif df['시군구명'][i].find('세종') == 0:
                    si_name[i] = '세종'
                else :
                    si_name[i] = df['시군구명'][i][:-1] # 세종, 광명, 김포, 강릉
            else : 
                admin_gu = df['시군구명'][i].split()[-1]
                for key, value in tmp_gu_dict.items():
                    if admin_gu in value:
                        if len(admin_gu) == 2:
                            # 포항 북구, 포항 남구
                            si_name[i] = key + ' ' + admin_gu
                        elif len(admin_gu) == 5:
                            # 창원 합포, 창원 회원
                            si_name[i] = key + ' ' + admin_gu[2:-1]
                        else : # 수원 팔달, 용인 수지
                            si_name[i] = key + ' ' + admin_gu[:-1]
    return si_name

# si_name을 통해서 ID를 두글자로 만들겠다는 for문